# Generated by Django 4.1.7 on 2023-08-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='department',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='info',
            name='enrollment',
            field=models.IntegerField(default=0),
        ),
    ]
