# Generated by Django 4.1.7 on 2023-09-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_info_department_info_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='enrollment',
            field=models.IntegerField(unique=True),
        ),
    ]
