# Generated by Django 4.1.7 on 2023-09-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_info_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.EmailField(default='huehue@gmail.com', max_length=254, unique=True),
        ),
    ]
