# Generated by Django 4.1.7 on 2023-09-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_info_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='experience',
            field=models.CharField(default='Not Specified', max_length=200),
        ),
    ]
